# AAI614: Data Science & its Applications

*Notebook 2.1: Practice with Pandas*

<a href="https://colab.research.google.com/github/harmanani/AAI614/blob/main/Week%202/Notebook2.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*This notebook contains excerpts from the [Pandas in Action](https://www.manning.com/books/pandas-in-action) by Boris Paskhaver.*

### 1. Read the file

In [317]:
import pandas as pd
import numpy as np
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

nba = pd.read_csv("https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/nba.csv")

### 1. Shared and Exclusive Attributes between Series and DataFrames

In [318]:
pd.Series([1, 2, 3]).dtype

dtype('int64')

In [319]:
nba.dtypes

Name        object
Team        object
Position    object
Birthday    object
Salary       int64
dtype: object

In [320]:
nba.dtypes.value_counts()

object    4
int64     1
Name: count, dtype: int64

In [321]:
nba.index

RangeIndex(start=0, stop=450, step=1)

In [322]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [323]:
nba.ndim

2

In [324]:
nba.shape

(450, 5)

In [325]:
nba.size

2250

In [326]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [327]:
nba.count().sum()

2250

In [328]:
data = {
    "A": [1, np.nan],
    "B": [2, 3]
}

df = pd.DataFrame(data)
df

     A  B
0  1.0  2
1  NaN  3

In [329]:
df.size

4

In [330]:
df.count()

A    1
B    2
dtype: int64

In [331]:
df.count().sum()

3

### 2. Shared Methods between Series and DataFrames

In [332]:
nba.head(2)

             Name                Team Position Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG  9/26/96  1445697
1  Christian Wood     Detroit Pistons       PF  9/27/95  1645357

In [333]:
nba.tail(n = 3)

              Name                 Team Position  Birthday    Salary
447    Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448  Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449    Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

In [334]:
nba.tail()

              Name                 Team Position  Birthday    Salary
445  Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446    Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447    Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448  Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449    Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

In [335]:
nba.sample(3)

                 Name                   Team Position Birthday    Salary
64        Theo Pinson          Brooklyn Nets       SG  11/5/95   1445697
65   Danilo Gallinari  Oklahoma City Thunder       PF   8/8/88  22615559
404    Doug McDermott         Indiana Pacers       PF   1/3/92   7333333

In [336]:
nba.nunique()

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [337]:
nba.max()

Name            Zylan Cheatham
Team        Washington Wizards
Position                    SG
Birthday                9/9/93
Salary                40231758
dtype: object

In [338]:
nba.min()

Name         Aaron Gordon
Team        Atlanta Hawks
Position                C
Birthday          1/10/98
Salary              79568
dtype: object

In [339]:
nba.nlargest(n = 4, columns = "Salary")

                  Name                   Team Position  Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG   3/14/88  40231758
38          Chris Paul  Oklahoma City Thunder       PG    5/6/85  38506482
219  Russell Westbrook        Houston Rockets       PG  11/12/88  38506482
251          John Wall     Washington Wizards       PG    9/6/90  38199000

In [340]:
nba['Birthday'] = pd.to_datetime(nba['Birthday'])

/var/folders/7c/dnx_f4dn5jlcgjk9d2b920zh0000gn/T/ipykernel_44399/101016257.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba['Birthday'] = pd.to_datetime(nba['Birthday'])

In [341]:
nba.nsmallest(n = 3, columns = ["Birthday"])

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

#### The following should give an error.  No need to panic :-)

In [342]:
#nba.sum()

TypeError: 'DatetimeArray' with dtype datetime64[ns] does not support reduction 'sum'

In [ ]:
nba.sum(numeric_only = True)

In [ ]:
nba.mean(numeric_only = True)

In [ ]:
nba.median(numeric_only = True)

In [ ]:
nba.mode(numeric_only = True)

In [ ]:
nba.std(numeric_only = True)

## 3. Sorting a DataFrame

### 3.1 Sorting by Single Column

In [ ]:
# The two lines below are equivalent
nba.sort_values("Name")
nba.sort_values(by = "Name")

In [ ]:
nba.sort_values("Name", ascending = False).head()

In [ ]:
nba.sort_values("Birthday", ascending = False).head()

### 4.2 Sorting by Multiple Columns

In [ ]:
nba.sort_values(by = ["Team", "Name"])

In [ ]:
nba.sort_values(["Team", "Name"], ascending = False)

In [ ]:
nba.sort_values(
    by = ["Team", "Salary"], ascending = [True, False]
)

In [ ]:
nba = nba.sort_values(
    by = ["Team", "Salary"],
    ascending = [True, False]
)

## 5 Sorting by Index

In [ ]:
nba.head()

### 5.1 Sorting by Row Index

In [ ]:
# The two lines below are equivalent
nba.sort_index().head()
nba.sort_index(ascending = True).head()

In [ ]:
nba.sort_index(ascending = False).head()

In [ ]:
nba = nba.sort_index()

### 5.2 Sorting by Column Index

In [ ]:
# The two lines below are equivalent
nba.sort_index(axis = "columns").head()
nba.sort_index(axis = 1).head()

In [ ]:
nba.sort_index(axis = "columns", ascending = False).head()

## 5.3 Setting a New Index

In [ ]:
# The two lines below are equivalent
nba.set_index(keys = "Name")
nba.set_index("Name")

## 6 Selecting Columns and Rows from a DataFrame

### 6.1 Selecting a Single Column from a DataFrame

In [ ]:
nba.Salary

In [ ]:
nba["Position"]

### 6.2 Selecting Multiple Columns from a DataFrame

In [ ]:
nba[["Salary", "Birthday"]].head()

In [ ]:
nba[["Birthday", "Salary"]].head()

In [ ]:
nba.select_dtypes(include = "object")

In [ ]:
nba.select_dtypes(exclude = ["object", "int"])

## 7 Selecting Rows from a DataFrame

### 7.1 Extracting Rows by Index Label

In [ ]:
nba

In [ ]:
nba.index = nba["Name"]

In [ ]:
nba.loc["LeBron James"]

In [ ]:
nba.loc[["Kawhi Leonard", "Paul George"]]

In [ ]:
nba.loc[["Paul George", "Kawhi Leonard"]]

In [ ]:
nba.sort_index().loc["Otto Porter":"Patrick Beverley"]

In [ ]:
players = ["Otto Porter", "PJ Dozier", "PJ Washington"]
players[0:2]

In [ ]:
nba.sort_index().loc["Zach Collins":]

In [ ]:
nba.sort_index().loc[:"Al Horford"]

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [ ]:
#nba.loc["Bugs Bunny"]

### 7.2 Extracting Rows by Index Position

In [ ]:
nba.iloc[300]

In [ ]:
nba.iloc[[100, 200, 300, 400]]

In [ ]:
nba.iloc[400:404]

In [ ]:
nba.iloc[:2]

In [ ]:
nba.iloc[447:]

In [ ]:
nba.iloc[-10:-6]

In [ ]:
nba.iloc[0:10:2]

### 7.3 Extracting Values from Specific Columns

In [ ]:
nba['Team'].loc["Giannis Antetokounmpo"]

In [ ]:
nba.loc["James Harden", ["Position", "Birthday"]]

In [ ]:
nba.loc[
    ["Russell Westbrook", "Anthony Davis"],
    ["Team", "Salary"]
]

In [ ]:
nba.loc["Joel Embiid", "Position":"Salary"]

In [ ]:
nba.loc["Joel Embiid", "Salary":"Position"]

In [ ]:
nba.iloc[57, 3]

In [ ]:
nba.iloc[100:104, :3]

In [ ]:
nba.at["Austin Rivers", "Birthday"]

In [ ]:
nba.iat[263, 1]

In [ ]:
%%timeit
nba.at["Austin Rivers", "Birthday"]

In [ ]:
%%timeit
nba.loc["Austin Rivers", "Birthday"]

In [ ]:
%%timeit
nba.iat[263, 1]

In [ ]:
%%timeit
nba.iloc[263, 1]

## 8 Extracting Values from Series

In [ ]:
nba["Salary"].loc["Damian Lillard"]

In [ ]:
nba["Salary"].at["Damian Lillard"]

In [ ]:
nba["Salary"].iloc[234]

In [ ]:
nba["Salary"].iat[234]

## 9 Renaming Columns or Rows

In [ ]:
nba.columns

In [ ]:
nba.columns = ["Team", "Position", "Date of Birth", "Pay"]
nba.head(1)

In [ ]:
nba.rename(columns = { "Date of Birth": "Birthday" })

In [ ]:
nba = nba.rename(columns = { "Date of Birth": "Birthday" })

In [ ]:
nba.loc["Giannis Antetokounmpo"]

In [ ]:
nba = nba.rename(
    index = { "Giannis Antetokounmpo": "Greek Freak" }    
)

In [ ]:
nba.loc["Greek Freak"]

## 10 Resetting an Index

In [ ]:
nba.set_index("Team").head()

In [ ]:
nba.reset_index().head()

In [ ]:
nba.reset_index().set_index("Team").head()

In [ ]:
nba = nba.reset_index().set_index("Team")